name: 3. Get Movies

on:
  repository_dispatch:
    types: [start-get-movies]
  workflow_dispatch:  # Permite acionamento manual também

jobs:
  get-movies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      
      - name: Install dependencies
        run: pipenv install
          
      - name: Scraping movie data
        run: |
          echo "=============================="
          echo "Scraping movie data from site."
          echo "=============================="
          pipenv run python ./scraping/get_movies_to_update.py
          echo "Finished scraping movie data from site"
        env:
          CONNECTION_URL: ${{ secrets.CONNECTION_URL }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
      
      # Acionar o próximo workflow
      - name: Trigger next workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.WORKFLOW_PAT }}
          event-type: start-create-training-data