name: Weekly Database Update and Railway Deploy

on:
  schedule:
    # Executa uma vez por semana às segundas-feiras, às 1:00 da manhã UTC
    - cron: '0 1 * * 1'
  workflow_dispatch:  # Permite acionamento manual também

# Adicione esta seção para dar permissão de escrita ao token GITHUB_TOKEN
permissions:
  contents: write

jobs:
  get-popular-users:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      
      - name: Install dependencies
        run: pipenv install
          
      - name: Scraping popular users
        run: |
          pipenv run python ./scraping/get_popular_user.py
        env:
          CONNECTION_URL: ${{ secrets.CONNECTION_URL }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
  
  get-ratings:
    needs: get-popular-users
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      
      - name: Install dependencies
        run: pipenv install
          
      - name: Scraping ratings
        run: |
          pipenv run python ./scraping/get_ratings.py
        env:
          CONNECTION_URL: ${{ secrets.CONNECTION_URL }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
  
  get-movies:
    needs: get-ratings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      
      - name: Install dependencies
        run: pipenv install
          
      - name: Scraping movie data
        run: |
          pipenv run python ./scraping/get_movies.py
        env:
          CONNECTION_URL: ${{ secrets.CONNECTION_URL }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
  
  create-training-data-and-deploy:
    needs: get-movies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      
      - name: Install dependencies
        run: pipenv install
          
      - name: Creating training data
        run: |
          pipenv run python ./model/create_training_data.py
        env:
          CONNECTION_URL: ${{ secrets.CONNECTION_URL }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
          
      - name: Commit and push updated data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/ model/
          git commit -m "Atualização semanal automática dos dados e modelos" || echo "No changes to commit"
          git push
          
      - name: Install Railway CLI
        run: npm i -g @railway/cli
          
      - name: Deploy to Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}